= The Walking Dead 400 days guide: convincing everyone to join Tavia
:published_at: 2013-07-12
:hp-tags: The Walking Dead, Games

This guide will show you how to convince everyone to join Tavia at the end of "The Walking Dead: 400 Days". In each chapter, there are couple of options which might affect the character's decision of joining Tavia.


== Wyatt
Either Wyatt or Eddie has to check _the guy_ after hitting him, while being chased by an unknown man. You have to *stay in the car* and *leave Eddie behind* as this will give Wyatt a reason to join Tavia.

Next, you have to *refuse Eddie's suggestion of playing rock-paper-scissors to decide who checks the body*. This will make Eddie go and check the body himself.
Or you can accept and play rock-paper-scissors, but you have to win. Losing will cause Eddie to leave Wyatt behind and that is not the option you are looking for.

== Vince 
When Vince is in the bus, you will have to chop-off either of Justin or Danny's ankle in order to take the chain off. *Shoot Danny's ankle*.
Running away with Justin (shooting Danny's ankle) will teach Vince that shelters are important, while running away with Danny (Shooting Justin's ankle) will teach him not to trust anyone as this will affect his trust towards Tavia, resulting not going with her.

== Russell
At the end of Russell's chapter, you have two options where you get to decide either joining or leaving Nate. *Leaving him will make Russell more likely to join Tavia*, but this is largely affected by the way Tavia convinces him.

== Shel
Killing or freeing the stranger will not affect Shel's decision but killing Stephanie will. When you talk to Becca, *take the keys and drive the RV away*. As Becca mentions, Roman will hunt them down. This will give Shel a reason to join Tavia.

== Bonnie
Bonnie is the last one because she will be the first one to join Tavia; no matter what your choices were. You can lie to Leland about Dee's death or tell him the truth. You can also leave him to die. _None of the choices will affect her decision_.

== Tavia
In Tavia's chapter, you will have to recruit as much members from the camp as possible. To do so, follow these choices:

. "I followed the smoke" or "I found your notes"
. "What would you have me do to convince you?" _(This one is important to convince Russell)_
. "You outnumber me"
. "You might find people you know" _(This one is also important to convince Russell)_
. "I give you my word"

Russell becomes nervous when Tavia comes. Regardless of your previous choice regarding Nate's fate, he won't join Tavia unless she says "You might find people you know" as this will give him hope to find his family.